"""add sales_order_id to logistics

Revision ID: 4de2fb196634
Revises: 22509d525ce5
Create Date: 2026-04-26 15:33:35.402565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de2fb196634'
down_revision = '22509d525ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logistics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sales_orders', ['sales_order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logistics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sales_order_id')

    # ### end Alembic commands ###
