"""Updated name length and added mobile column

Revision ID: afd7f07d7f58
Revises: 1040f78118d0
Create Date: 2026-04-14 15:36:58.186657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd7f07d7f58'
down_revision = '1040f78118d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'])

    with op.batch_alter_table('logistics', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'])
        batch_op.create_foreign_key(None, 'sites', ['site_id'], ['site_id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'subcategories', ['subcategory_id'], ['id'])

    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'])
        batch_op.create_foreign_key(None, 'sites', ['site_id'], ['site_id'])

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['customer_id'])
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'])
        batch_op.create_foreign_key(None, 'sites', ['site_id'], ['site_id'])

    with op.batch_alter_table('seasonal_planning', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sites', ['site_id'], ['site_id'])

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'states', ['state_id'], ['state_id'])

    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('seasonal_planning', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('logistics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('product_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
