"""Updated name length and added mobile column

Revision ID: f0c2ac6b0f2d
Revises: 8792543a3e04
Create Date: 2026-05-15 14:49:52.501645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c2ac6b0f2d'
down_revision = '8792543a3e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
